[package]
name = "rlisp"
version = "0.1.0"
authors = ["Aaron Eline <aeline@umd.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logos = "0.11.4"
num-bigint = "0.3.0"
num-traits = "0.2.12"
ctrlc = "3.1.4"
